name: jaspr_lucide
description: Jaspr SVG components for Lucide.
version: 0.20.0
homepage: https://github.com/dazemc/jaspr_lucide
repository: https://github.com/dazemc/jaspr_lucide.git
issue_tracker: https://github.com/dazemc/jaspr_lucide/issues

topics:
  - jaspr
  - web
  - html
  - css
  - icons

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  xml: ^6.6.1
  jaspr: ^0.22.0
  custom_lint: ^0.8.1

dev_dependencies:
  analysis_options: any
  jaspr_lints: ^0.6.0
  lints: ^6.0.0
